export enum RoleEnum {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  OWNER = 'OWNER',
  SUPERVISOR = 'SUPERVISOR',
  COUNTERMAN = 'COUNTERMAN',
  DECKMAN = 'DECKMAN',
  CABINMAN = 'CABINMAN',
}
